#%RAML 1.0 DataType
type: object 
properties:
  business: 
    type: string
    required: true
    example: "abarrotes Carmen"
  name:
    type: string
    required: true
    example: "carmen"
  last_name:
    type: string
    required: true
    example: "taboada"
  phone:
    type: number
    required: true
    example: 1234567890
  userName:
    type: string
    required: true
    example: "carment"
  password:
    type: string
    required: true
    example: "123456"