#%RAML 1.0
title: tn-store-movil-api-svc
types:
  register_admin: !include /data_type/dataType.raml
/register:
  post:
    description: este servicio regitra al administrador de la compania
    body:
      application/json:
        type: register_admin
        example: !include /examples/request/post_register.json
    responses:
      200:
        body:
            application/json:
                example: !include /examples/response/post_register.json